#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use PrivatePackagist\ApiClient\Client;

$packageName = $argv[1];
$packagistApiToken = $argv[2];
$packagistApiSecret = $argv[3];
$client = new Client();
$client->authenticate($packagistApiToken, $packagistApiSecret);
$packages = $client->packages()->listDependents($packageName);
$urls = [];
foreach ($packages as $package) {
    $urls[] = ['repository' => ltrim(parse_url($package['config']['url'], PHP_URL_PATH), '/')];
}
echo json_encode($urls);
