#!/usr/bin/env php
<?php
// application.php

var_dump($argv);

//require __DIR__.'/vendor/autoload.php';
//
//use Symfony\Component\Console\Application;
//
//$application = new Application();
//$action = new ActionCommand();
//
//$application->add($action);
//$application->run();
